name = "StochasticCharacterMap"
uuid = "ae31c2cd-9e44-4783-99a9-c92c40e34db9"
authors = ["Bjorn Tore Kopperud <kopperud@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CairoMakie = "0.13.2"
Distributions = "0.25.118"
Random = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
